spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/gift_certificates_v2
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: dev3469


---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://prod-server:5432/gift_certificates
    driver-class-name: org.postgresql.Driver
    username: admin
    password: password