spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

application:
  security:
    jwt:
      token:
        secret-key: 7134743777217A25432A462D4A614E645267556B58703272357538782F413F44
        issuer: https://gift-certificates.app
        expiration: 3600000

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/gift_certificates_v2
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: dev3469


---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://prod-server:5432/gift_certificates
    driver-class-name: org.postgresql.Driver
    username: admin
    password: password